### ISSUE TITLE
可以仿照这个做一个HEP版的吗？

### ISSUE THREAD

**Issue by 123-wqy** [ygcaicn/keledge#1]
HEP（高教社）貌似预览界面和请求的authorize和可知一样，就是js可能略有改动
希望能够顺便添加对HEP的支持~
地址：[https://ebook.hep.com.cn/ebooks/index.html#/]()
js：https://ebook.hep.com.cn/ebooks/read/static/js/3.3fe9d02c34f5e5a3fc36.1582624883446.js
感谢感谢

**Comment by ygcaicn** [comment]
有时间可以考虑

**Comment by ygcaicn** [comment]
已添加 高教书苑、悦读的支持。

**Comment by 123-wqy** [comment]
OK，感谢！已star
