### ISSUE TITLE
pdf无法打开

### ISSUE THREAD

**Issue by Junix-honor** [ygcaicn/keledge#10]
下载完的pdf打不开

**Comment by 123-wqy** [comment]
确保_dec文件夹内有文件，打开里面的PDF

**Comment by Junix-honor** [comment]
> 确保_dec文件夹内有文件，打开里面的PDF
不是《书名》_enc里面吗？打开了pdf，但是adobe acrobat 显示文件错误

**Comment by 123-wqy** [comment]
> > 确保_dec文件夹内有文件，打开里面的PDF
> > 不是《书名》_enc里面吗？打开了pdf，但是adobe acrobat 显示文件错误

那个是加密的原始文件，具体见第二个issue
https://github.com/ygcaicn/keledge/issues/2
