### ISSUE TITLE
可以做个这个网页的吗？

### ISSUE THREAD

**Issue by LML-566** [ygcaicn/keledge#11]
可以做个这个网页的吗？
http://sjzk.spacespecial.com.cn/#/home/book

**Comment by 123-wqy** [comment]
这个网页好像可知改版前的私钥获取...
详情看这里
https://www.52pojie.cn/thread-1099828-1-1.html
实测没问题

**Comment by sdieedu** [comment]
同意楼上的

**Comment by ligxi** [comment]
这个楼主自己按照二楼的链接里给的思路研究研究就知道怎么解了。已经白嫖这么多了，再做出来一个工具来，那这个网站恐怕要遭殃了，还是不要给这个网站添乱了吧。楼主如果真的感兴趣可以专研一下，能学到不少技术哦。
