### ISSUE TITLE
keledge平台好像失效了？

### ISSUE THREAD

**Issue by Junix-honor** [ygcaicn/keledge#13]
keledge平台没有弹出窗口

**Comment by ygcaicn** [comment]
#9

**Comment by Junix-honor** [comment]
> [＃9](https://github.com/ygcaicn/keledge/issues/9)

现在在本地用main.py一运行就暂时性封号了

**Comment by 123-wqy** [comment]
> > [＃9](https://github.com/ygcaicn/keledge/issues/9)
> 
> 现在在本地用main.py一运行就暂时性封号了

有解决方法
本质问题是访问https://gateway.keledge.com/transfer/filetranslate 就被ban号
可以模仿网页请求，把这个网址替换掉
这样既不会封号，也不会触发限制

**Comment by 123-wqy** [comment]
比如这个地址
https://gateway.keledge.com/transfer/filetranslate/6E7C9EFCB8B83D3116665DDCD72E30D5292DBEF6.pdf??q=XXXXXX省略...
只要应用正则替换
把https://gateway.keledge.com/transfer/filetranslate.(.*?).pdf?
替换为https://phei.keledge.com:50002/transfer/dcd/net/content/stream
（具体根据出版社有所不同）
最后再应用普通替换把两个问号“??”替换成一个问号“?”即可

**Comment by sdieedu** [comment]
> 比如这个地址
> [https://gateway.keledge.com/transfer/filetranslate/6E7C9EFCB8B83D3116665DDCD72E30D5292DBEF6.pdf??q=XXXXXX省略](https://gateway.keledge.com/transfer/filetranslate/6E7C9EFCB8B83D3116665DDCD72E30D5292DBEF6.pdf??q=XXXXXX%E7%9C%81%E7%95%A5)...
> 只要应用正则替换
> 把https://gateway.keledge.com/transfer/filetranslate.(.*?).pdf?
> 替换为https://phei.keledge.com:50002/transfer/dcd/net/content/stream
> （具体根据出版社有所不同）
> 最后再应用普通替换把两个问号“??”替换成一个问号“?”即可

电子工业出版社为例：
是不是就是把https://gateway.keledge.com/transfer/filetranslate  替换为
https://phei.keledge.com:50002/transfer/dcd/net/content/stream

**Comment by 123-wqy** [comment]
> > 比如这个地址
> > [https://gateway.keledge.com/transfer/filetranslate/6E7C9EFCB8B83D3116665DDCD72E30D5292DBEF6.pdf??q=XXXXXX省略](https://gateway.keledge.com/transfer/filetranslate/6E7C9EFCB8B83D3116665DDCD72E30D5292DBEF6.pdf??q=XXXXXX%E7%9C%81%E7%95%A5)...
> > 只要应用正则替换
> > 把https://gateway.keledge.com/transfer/filetranslate.(.*?).pdf?
> > 替换为https://phei.keledge.com:50002/transfer/dcd/net/content/stream
> > （具体根据出版社有所不同）
> > 最后再应用普通替换把两个问号“??”替换成一个问号“?”即可
> 
> 电子工业出版社为例：
> 是不是就是把https://gateway.keledge.com/transfer/filetranslate 替换为
> https://phei.keledge.com:50002/transfer/dcd/net/content/stream

替换到pdf那里，留下q参数以及之后的部分
