### ISSUE TITLE
大神，指点一下呗？

### ISSUE THREAD

**Issue by ScienceZone** [ygcaicn/keledge#15]
您好，很遗憾您将这个项目关闭了，但是还是冒昧来请教一下，请问这种疫情期间免费看的书怎么下载？https://www.keledge.com/pdfReader?url=https%3A%2F%2Fgateway.keledge.com%2Ftransfer%2Faqr%2Fauthorize&contentexternalid=P00056-01-9787519119706-Pdf&id=676668936145604608&organizationExternalId=&objectType=104&process=&tocValue=
指点一下下载后怎么解密就行，里面第一页地址是这样的https://gateway.keledge.com/transfer/filetranslate/shorturl/311e99a35582121be4029d5129a406c0/c6fe63b20b1c59cc10964cf8d4ec6298.pdf?fn=f690229642a2b8bc66e9fbb05793266b，下载后打开是乱码？有些阅读器显示文档结构已损坏，麻烦您抽空指点一下，谢谢！！

**Comment by 123-wqy** [comment]
可帮下

**Comment by ygcaicn** [comment]
> 您好，很遗憾您将这个项目关闭了，但是还是冒昧来请教一下，请问这种疫情期间免费看的书怎么下载？https://www.keledge.com/pdfReader?url=https%3A%2F%2Fgateway.keledge.com%2Ftransfer%2Faqr%2Fauthorize&contentexternalid=P00056-01-9787519119706-Pdf&id=676668936145604608&organizationExternalId=&objectType=104&process=&tocValue=
> 指点一下下载后怎么解密就行，里面第一页地址是这样的[https://gateway.keledge.com/transfer/filetranslate/shorturl/311e99a35582121be4029d5129a406c0/c6fe63b20b1c59cc10964cf8d4ec6298.pdf?fn=f690229642a2b8bc66e9fbb05793266b，下载后打开是乱码？有些阅读器显示文档结构已损坏，麻烦您抽空指点一下，谢谢！！](https://gateway.keledge.com/transfer/filetranslate/shorturl/311e99a35582121be4029d5129a406c0/c6fe63b20b1c59cc10964cf8d4ec6298.pdf?fn=f690229642a2b8bc66e9fbb05793266b%EF%BC%8C%E4%B8%8B%E8%BD%BD%E5%90%8E%E6%89%93%E5%BC%80%E6%98%AF%E4%B9%B1%E7%A0%81%EF%BC%9F%E6%9C%89%E4%BA%9B%E9%98%85%E8%AF%BB%E5%99%A8%E6%98%BE%E7%A4%BA%E6%96%87%E6%A1%A3%E7%BB%93%E6%9E%84%E5%B7%B2%E6%8D%9F%E5%9D%8F%EF%BC%8C%E9%BA%BB%E7%83%A6%E6%82%A8%E6%8A%BD%E7%A9%BA%E6%8C%87%E7%82%B9%E4%B8%80%E4%B8%8B%EF%BC%8C%E8%B0%A2%E8%B0%A2%EF%BC%81%EF%BC%81)

参考  #9

**Comment by ScienceZone** [comment]
试了一下，还是没找到rsa私钥，可能我没看懂，再稍微详细指点一下呗，各位大神！？谢谢！

**Comment by ScienceZone** [comment]
其实我只是想下载《信息技术》那几本书而已：http://jkzx.esph.com.cn/teacherfree/index.html

**Comment by 123-wqy** [comment]
> 其实我只是想下载《信息技术》那几本书而已：http://jkzx.esph.com.cn/teacherfree/index.html

帮你下了
https://lanzous.com/ictavhe
目录没加，zip里有软件
目前方法不能用的原因是因为网站更改了js，重写后还能勉强继续用用

**Comment by ygcaicn** [comment]
![image](https://user-images.githubusercontent.com/17684070/82430891-8d1b5b00-9ac0-11ea-8875-506816d00354.png)

**Comment by ScienceZone** [comment]
非常感谢！

**Comment by BigfanofGreenDay** [comment]
大神能否帮忙下本书，高等教育出版社的版权保护实在太强了，其他地方找不到了😂https://ebook.hep.com.cn/ebooks/index.html#/
ISBN：【978-7-04-051421-6】如能帮忙，感激不尽！

**Comment by BigfanofGreenDay** [comment]
> > 其实我只是想下载《信息技术》那几本书而已：http://jkzx.esph.com.cn/teacherfree/index.html
> 
> 帮你下了
> https://lanzous.com/ictavhe
> 目录没加，zip里有软件
> 目前方法不能用的原因是因为网站更改了js，重写后还能勉强继续用用

大神能否帮忙下本书，高等教育出版社的版权保护实在太强了，其他地方找不到了😂https://ebook.hep.com.cn/ebooks/index.html#/
ISBN：【978-7-04-051421-6】如能帮忙，感激不尽！

**Comment by ygcaicn** [comment]
> > > 其实我只是想下载《信息技术》那几本书而已：http://jkzx.esph.com.cn/teacherfree/index.html
> > 
> > 
> > 帮你下了
> > https://lanzous.com/ictavhe
> > 目录没加，zip里有软件
> > 目前方法不能用的原因是因为网站更改了js，重写后还能勉强继续用用
> 
> 大神能否帮忙下本书，高等教育出版社的版权保护实在太强了，其他地方找不到了https://ebook.hep.com.cn/ebooks/index.html#/
> ISBN：【978-7-04-051421-6】如能帮忙，感激不尽！

留下email
