### ISSUE TITLE
怎么用的？

### ISSUE THREAD

**Issue by LML-566** [ygcaicn/keledge#2]
您说的是从第三步开始，那我来说说我的疑问。
------------------------------------------------------------------------------------
第三步原理：利用Chrome插件重定向Js地址到我们fake的Js, 保存图书信息以及加密密码。
问题一：Gooreplacer打不开，要科学上网吗？
问题二：Destination那个js是指本github里的，那么Source的那个JS怎么来的？

比如：https://www.keledge.com/wrap/details/book?id=620876602959466496怎么获取Source的那个JS？
您写的说明新手太不友好了，请具体一步步说明。

**Comment by 123-wqy** [comment]
Gooreplacer是Google store的，自然要FQ
那两个JS参数都是固定的，填进去就好
如果下的插件是中文版，匹配的类型应该是正则
另外，你要的书已经发了

**Comment by LML-566** [comment]
刚刚测试都正常下载那俩txt，现在反复跳出github给个star导致无法使用。。。，点×也不对，点执行脚本又会反复跳出github给个star，如此循环。。。

**Comment by ygcaicn** [comment]
1. Chrome插件商店需要梯子

2. Source分析出来的，直接copy即可。

刚才出问题是我提交了调试代码。

**Comment by LML-566** [comment]
我运行程序会报错，然后我就用python修改了一些代码在pycharm运行的：
您的源代码部分：
# parser = argparse.ArgumentParser()
    # parser.add_argument('-a', dest='authorize_file', required=True, action='store',
    #                 help='authorize file')
    # parser.add_argument('-p', dest='passwd_file', action='store',
    #                 help='passwd file')
    # parser.add_argument('-t', dest='sleep',type=int, default=0, action='store',
    #                 help='sleep time in second')
    # args = parser.parse_args()
    # authorize_file = args.authorize_file
    # base_dir = os.path.dirname(authorize_file)
    # book_prefix = os.path.basename(authorize_file).replace('_authorize.txt','')
    # if args.passwd_file is None:
    #     passwd_file = os.path.join(base_dir, book_prefix+"_passwd.txt")
    #     if not os.path.exists(passwd_file):
    #         logging.warning("[未找到passwd文件，请使用-p指定]")
    #         parser.print_help()
    #         exit(1)
我修改的：（让它直接运行，先不给他参数那些）
    authorize_file = 'E:/Test/kezhiwang/keledge-master/keledge-master/0_authorize.txt'
    passwd_file = 'E:/Test/kezhiwang/keledge-master/keledge-master/0_passwd.txt'
    base_dir = os.path.dirname(authorize_file)
    book_prefix = os.path.basename(authorize_file).replace('_authorize.txt','')
后面还有一处args.sleep改成了300（应该没有args参数了）
--------------------------运行结果-----------------------------------------------
C:\Users\Liu\Anaconda3\envs\python36\python.exe E:/Test/kezhiwang/keledge-master/keledge-master/main.py
全书共262页
WARNING: authorize_file未获取全文，请确保你的帐号拥有阅读全文的权限！
authorize_file获取261页
WARNING: {'WordCount': 0, 'NumberOfPage': 2, 'Url': 'https://gateway.keledge.com/transfer/filetranslate/64ECA79775710B1C0121C0B5AF55874EC643E4BC.pdf??q=Yjqzhk4LiuBpUhVJNwdWtukUnOtlQuj%2bMaMqhsVa85d3eSW8WzlpdDf9iVtt66VsntVmrZp6vNt6mdHHlGmtuQAnsDs%2bwHnGDsezbdSLDro%3d&BridgePlatformName=aqrcloud_web&fn=SSMLUKmbQ0zn41dYgOIpkQ==&fixedUrl=LNkZX2V_4GzK2Ws3z_nqt6xzZI7ejOhBU4o_FuSyiwg-FU3tZWWcC1B2Dw1AajrOHjbhdGbW7h5oVT5TNhauzBpuLP8Fb5_H33Wo2cYHNtfVcceELOkMqwKFX7ZoylDZ9nLjezxiZuQyQ8ekH_KXp_lncRP9Y6og7HTYQvvRmc4xgQ4dsqi5b8zn-0ccz0-J7tbDvY3AqQibC82X-0o-_3GmjO8awEcJkPPaqr78HE-aQEmxdYu9hX9mUz_RPtw1EF_sBMtlszTFQ-lbkkNig1G35dn6jnJ43-yz7FagBBRY8Y3fVBrFvIOA5mHQHNRxnFukVyxbdC1zL3wEkWshpQ==&filetoken=XLlM0gIM7VUK4gq-KPv8beucZoUfNGgfhIg6iOB1lHUiRDZF1tt3Y94qfdn9LlMjcx6gqVvq7ImFsfGOodMbEyFfafyUEwW-OE_pc1cagrwzQGddxdNrGOk-WdCOBWykPmy36uOlwZamy3BdJtrqH5yoO3UWtECDIdYCYNATG4HcGz-kRmvTgQ4DDjol-vlS14r_yuQvsQbfPJojm4CDUiyh6eMtWVIHZkrrQNHfGPcxMyjkPl4Ko8_tG3Hs2XYI_1Tpf9nWDFaRpkWG11i7VX_eT-3gtEycuZ5eZrn6Vjs_vgxz6r2boE6WxhKlkScvuf7wnhh0OALm4EmZyvAiDmu3ZQAsXHU-X2hU2yUOxKMhldDWf33VW8P4EdM0MFDMIR7KlwbekibDFLguAYBIgw=='} generated an exception: [WinError 183] 当文件已存在时，无法创建该文件。: 'E:/Test/kezhiwang/keledge-master/keledge-master\\0_enc'

Process finished with exit code -1
=======================================================
在0_enc下载了6个PDF，123456
均打不开，显示已损坏。

**Comment by ygcaicn** [comment]
xx_enc是加密的pdf，下载完才会解密。
附上xx_authorize.txt和passwd.txt

**Comment by LML-566** [comment]
是不是因为我i没有全文阅读权限？但我去找了本免费的试，
=========================================
谢枫 蒋腾旭.《OFFICE上机指导》.[Z].北京.中国财政经济出版社.2013.
摘要：未获取全文阅读权限！
本书总页数：103
获取到的页数：102
==========================================
就差一页
这个提示也没有全文阅读权限，请问可知的阅读权限是所有书都没有阅读权限吗？

==========================================
可不可以把自己有阅读权限比如这个102页下载下来？
我试过了，仍然是下载6页报错。

**Comment by ygcaicn** [comment]
![image](https://user-images.githubusercontent.com/17684070/76696008-6fe19f00-66c1-11ea-9741-32fb66ce29bc.png)
测试没有问题，无法复现。

**Comment by sdieedu** [comment]
能否写个word版本的？说明
网页版的图片显示不全，无法整理详细思路

**Comment by LML-566** [comment]
你在那个页面有没有提醒
摘要：未获取全文阅读权限！
本书总页数：103
获取到的页数：102
还是你的是获取的103页？

**Comment by ygcaicn** [comment]
> 你在那个页面有没有提醒
> 摘要：未获取全文阅读权限！
> 本书总页数：103
> 获取到的页数：102
> 还是你的是获取的103页？

tip:获取到的页数比总页数少1页，实际上已经是全文了，可忽略！

**Comment by ygcaicn** [comment]
> 能否写个word版本的？说明
> 网页版的图片显示不全，无法整理详细思路

图片都在仓库，clone或者下载zip到本地查看

**Comment by LML-566** [comment]
我尝试下载了，原来是我等的时间太短了，然后它报warning就把它停止了。
我下载后去干其他事，然后就下载好了102页。
但这102页每一页用Adobe Acrobat DC打不开，他也没有让我输入密码啥的，就说的PDF损坏，请问这是正常的吗？
我看第四步用PDFsam，那个只是一个合成软件吧，如果PDF可以正常打开，用Adobe Acrobat DC合并也可以吧

**Comment by ScienceZone** [comment]
大佬，你的教程看起来真是有点吃力！真得有点基础才行，不然一脸懵逼，现在还没看懂怎么操作，最好会基本电脑操作的人也能看懂，我得再试试看，希望能成功！谢谢您！

**Comment by 123-wqy** [comment]
> 我尝试下载了，原来是我等的时间太短了，然后它报warning就把它停止了。
> 我下载后去干其他事，然后就下载好了102页。
> 但这102页每一页用Adobe Acrobat DC打不开，他也没有让我输入密码啥的，就说的PDF损坏，请问这是正常的吗？
> 我看第四步用PDFsam，那个只是一个合成软件吧，如果PDF可以正常打开，用Adobe Acrobat DC合并也可以吧

看看那个解密的文件夹...
带_dec的...

**Comment by LML-566** [comment]
pdf在enc里面，dec里面为空。

**Comment by 123-wqy** [comment]
> pdf在enc里面，dec里面为空。

这不应该呀...
我下的时候脚本是会提示解密成功的...
装了openSSL吗？

**Comment by sdieedu** [comment]
Gooreplacer 已经设置按图设置好。登陆可知，打开了有有完全权限的书,如何获得那2个 核心txt？ 没有2020-03-10_18-13.png图示里面的下载按钮啊

**Comment by LML-566** [comment]
没有安装openSSL，因为运行过程中没有报openSSL的错，我疏忽了。请问这是软件还是库？
是通过pip install openSSL 安装吗？

**Comment by LML-566** [comment]
http://slproweb.com/products/Win32OpenSSL.html
这个网址上Win64 OpenSSL v1.1.1d Light和Win64 OpenSSL v1.1.1d下载哪个？还是都可以

**Comment by 123-wqy** [comment]
> http://slproweb.com/products/Win32OpenSSL.html
> 这个网址上Win64 OpenSSL v1.1.1d Light和Win64 OpenSSL v1.1.1d下载哪个？还是都可以

我下的是Win64OpenSSL-1_1_1d.exe，可以使用

**Comment by LML-566** [comment]
前147页还下载的好好的，但从148开始：
INFO: 下载失败：2_enc\148.pdf 200 https://gateway.keledge.com/transfer/filetranslate/FDE1D57E507BD6006DCDD5CD84759028303C2BF4.pdf??q=Yjqzhk4LiuBpUhVJNwdWtqNoU5CvyCs6uTpME6UkQer4XVQCnLKuaPe5amzzTjrCF6aWHRDidCi7nwQxIUcKCWnJL9hIfpeHq5waW4S%2f8Jk%3d&BridgePlatformName=aqrcloud_web&fn=gjZZN1QFhEV4yh7yCCRRvg==&fixedUrl=LNkZX2V_4GzK2Ws3z_nqt6xzZI7ejOhBU4o_FuSyiwg-FU3tZWWcC1B2Dw1AajrOHjbhdGbW7h5oVT5TNhauzBpuLP8Fb5_H33Wo2cYHNtd9p1hYz8Fz5IQSSvlslIeY9CZIvqlvoxRCGlVrYO8qFzf0PGoEAKrnhYnCnma2ShxVcpX_UoIYKWSlVVJLRw1Mec19p4wiBrSsw6o88VvY6lu1XB0GVviYmSjGPifolsi6FW0m4jHt-gHPcEWMkRjQWDrPGkDXTvOExST6kr0wHj2DPelBRjRsU7DlqBgQ2kPCZWveaaNynqb6spPYd7cpUmtaHrGAWE01PIA8uxRY5Q==&filetoken=XLlM0gIM7VUK4gq-KPv8beucZoUfNGgfhIg6iOB1lHUiRDZF1tt3Y94qfdn9LlMjSgGuCWaf6c8M1vVHtjHV4IQsNhw7kicmmGCW0zkPkkmrbykZjE34t2Ir9S1rl5KKPmy36uOlwZamy3BdJtrqH5yoO3UWtECDIdYCYNATG4HcGz-kRmvTgQ4DDjol-vlS14r_yuQvsQbfPJojm4CDUiyh6eMtWVIHZkrrQNHfGPcxMyjkPl4Ko8_tG3Hs2XYI_1Tpf9nWDFaRpkWG11i7VX_eT-3gtEycuZ5eZrn6VjuWgaDgsvmm_4h-rNUo7Ny1_2Ej4h7ICBsci5ugsZFf57jzLIg-n3rdDG4qJWCJQwUhldDWf33VW8P4EdM0MFDM-4LZDQdQDpXYmPcfPUyhRQ== size:75Bytes
{
  "Success": false,
  "Code": 34,
  "Description": "用户还未登录"
}
直到最后一页都是这个错误。

我是的登陆过后打开的一篇免费的文档，用插件下载的txt,但他说我未登录

WARNING: '99.pdf' generated an exception: __init__() got an unexpected keyword argument 'capture_output'
总共：241页
成功：0页

结果是enc里面有PDF，但是enc有这个文件夹，但里面是空空如也

**Comment by LML-566** [comment]
最后一行的第二个enc是dec,打错了

**Comment by 123-wqy** [comment]
> 前147页还下载的好好的，但从148开始：
> INFO: 下载失败：2_enc\148.pdf 200 https://gateway.keledge.com/transfer/filetranslate/FDE1D57E507BD6006DCDD5CD84759028303C2BF4.pdf??q=Yjqzhk4LiuBpUhVJNwdWtqNoU5CvyCs6uTpME6UkQer4XVQCnLKuaPe5amzzTjrCF6aWHRDidCi7nwQxIUcKCWnJL9hIfpeHq5waW4S%2f8Jk%3d&BridgePlatformName=aqrcloud_web&fn=gjZZN1QFhEV4yh7yCCRRvg==&fixedUrl=LNkZX2V_4GzK2Ws3z_nqt6xzZI7ejOhBU4o_FuSyiwg-FU3tZWWcC1B2Dw1AajrOHjbhdGbW7h5oVT5TNhauzBpuLP8Fb5_H33Wo2cYHNtd9p1hYz8Fz5IQSSvlslIeY9CZIvqlvoxRCGlVrYO8qFzf0PGoEAKrnhYnCnma2ShxVcpX_UoIYKWSlVVJLRw1Mec19p4wiBrSsw6o88VvY6lu1XB0GVviYmSjGPifolsi6FW0m4jHt-gHPcEWMkRjQWDrPGkDXTvOExST6kr0wHj2DPelBRjRsU7DlqBgQ2kPCZWveaaNynqb6spPYd7cpUmtaHrGAWE01PIA8uxRY5Q==&filetoken=XLlM0gIM7VUK4gq-KPv8beucZoUfNGgfhIg6iOB1lHUiRDZF1tt3Y94qfdn9LlMjSgGuCWaf6c8M1vVHtjHV4IQsNhw7kicmmGCW0zkPkkmrbykZjE34t2Ir9S1rl5KKPmy36uOlwZamy3BdJtrqH5yoO3UWtECDIdYCYNATG4HcGz-kRmvTgQ4DDjol-vlS14r_yuQvsQbfPJojm4CDUiyh6eMtWVIHZkrrQNHfGPcxMyjkPl4Ko8_tG3Hs2XYI_1Tpf9nWDFaRpkWG11i7VX_eT-3gtEycuZ5eZrn6VjuWgaDgsvmm_4h-rNUo7Ny1_2Ej4h7ICBsci5ugsZFf57jzLIg-n3rdDG4qJWCJQwUhldDWf33VW8P4EdM0MFDM-4LZDQdQDpXYmPcfPUyhRQ== size:75Bytes
> {
> "Success": false,
> "Code": 34,
> "Description": "用户还未登录"
> }
> 直到最后一页都是这个错误。
> 
> 我是的登陆过后打开的一篇免费的文档，用插件下载的txt,但他说我未登录
> 
> WARNING: '99.pdf' generated an exception: **init**() got an unexpected keyword argument 'capture_output'
> 总共：241页
> 成功：0页
> 
> 结果是enc里面有PDF，但是enc有这个文件夹，但里面是空空如也

下载过程中有时候会出现这个未登录错误，去网页里刷新一下或者重开脚本试试
下载完成没有解密文件说明解密过程有问题
正常情况下，控制台应该有类似下面的输出结果

> INFO: page 241.pdf decrypt ok.
INFO: page 245.pdf decrypt ok.
INFO: page 243.pdf decrypt ok.
INFO: page 253.pdf decrypt ok.
INFO: page 246.pdf decrypt ok.
INFO: page 251.pdf decrypt ok.
INFO: page 247.pdf decrypt ok.
INFO: page 249.pdf decrypt ok.
INFO: page 254.pdf decrypt ok.
INFO: page 250.pdf decrypt ok.

**Comment by LML-566** [comment]
这是我插件下载的txt：
https://www.lanzous.com/b089a3zcd 密码:e3gr
麻烦你试会不会遇到这个问题，我现在搞不清楚是我账号的问题还是软件环境的问题还是运行指令的问题
我是 python mian.py -a 1-authorize.txt运行的，有问题吗？

**Comment by LML-566** [comment]
我的账号是新申请的，没有任何高校相关的东西，是不是对于账号有特别的要求

**Comment by LML-566** [comment]
我就想今天晚上成功运行一次程序，心态都快被搞裂开了

**Comment by ScienceZone** [comment]
大佬，求解答！运行出错，哪里出问题了？ 
 File "E:\Toolbox\应用\下载工具\keledge-master\main.py", line 2, in <module>
    import requests
ImportError: No module named requests

**Comment by ScienceZone** [comment]
我用的指令是“main.py -a ~/Downloads/【书名】_authorize.txt”

**Comment by 123-wqy** [comment]
> 大佬，求解答！运行出错，哪里出问题了？
> File "E:\Toolbox\应用\下载工具\keledge-master\main.py", line 2, in
> import requests
> ImportError: No module named requests

注意pip install必要的包

**Comment by 123-wqy** [comment]
> 这是我插件下载的txt：
> https://www.lanzous.com/b089a3zcd 密码:e3gr
> 麻烦你试会不会遇到这个问题，我现在搞不清楚是我账号的问题还是软件环境的问题还是运行指令的问题
> 我是 python mian.py -a 1-authorize.txt运行的，有问题吗？

你这是哪本书？
我这里下载也是一样的问题......

**Comment by 123-wqy** [comment]
> 这是我插件下载的txt：
> https://www.lanzous.com/b089a3zcd 密码:e3gr
> 麻烦你试会不会遇到这个问题，我现在搞不清楚是我账号的问题还是软件环境的问题还是运行指令的问题
> 我是 python mian.py -a 1-authorize.txt运行的，有问题吗？

失败了几十次之后又继续下了...
神奇...

**Comment by ygcaicn** [comment]
> 我就想今天晚上成功运行一次程序，心态都快被搞裂开了

我测试了authorize.txt没有问题，打开cmd运行openssl验证openssl是否安装成功。
若openssl成功运行可可手动解密一页尝试，在enc文件夹运行如下指令：

`openssl enc -d -aes-128-ecb -K passwd.txt文件的内容 -in 1.pdf -out dec.pdf`

**Comment by ygcaicn** [comment]
> > 这是我插件下载的txt：
> > https://www.lanzous.com/b089a3zcd 密码:e3gr
> > 麻烦你试会不会遇到这个问题，我现在搞不清楚是我账号的问题还是软件环境的问题还是运行指令的问题
> > 我是 python mian.py -a 1-authorize.txt运行的，有问题吗？
> 
> 失败了几十次之后又继续下了...
> 神奇...

下载过快会出各种问题，可以使用-t参数减速

**Comment by LML-566** [comment]
https://www.keledge.com/wrap/details/book?id=635714382013140992
你的失败是报的什么错误？是账号未登录吗？你说它继续了是把所有的都下载了吗？
openssl按照你说的那个安装的：CMD中：
Microsoft Windows [版本 10.0.17763.1039]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\Liu>openssl
OpenSSL>
应该是成功了
你的dec里面有PDF吗？

**Comment by ygcaicn** [comment]
openssl安装正确的话enc文件夹下载好的都可以解密的，解密和帐号没有关系。我只有Linux环境无法在windows测试

**Comment by LML-566** [comment]
我换了高教书院的试试，结果下载完了dec里面空空如也，它报了一个错误，但是因为是在CMD运行的，所以不知道错误是什么，也看不懂，如果在pycharm里面运行还能知道错误是啥

**Comment by LML-566** [comment]
我再运行一次给你看错误

**Comment by LML-566** [comment]
(python36) E:\Test\kezhiwang\keledge-master>python main.py -a 3_authorize.txt
全书共130页
authorize_file获取129页
WARNING: authorize_file未获取全文，请确保你的帐号拥有阅读全文的权限！
INFO: 已存在！3_enc\1.pdf
INFO: 已存在！3_enc\2.pdf
INFO: 已存在！3_enc\3.pdf
INFO: 已存在！3_enc\4.pdf
...
INFO: 已存在！3_enc\128.pdf
INFO: 已存在！3_enc\129.pdf
WARNING: '10.pdf' generated an exception: __init__() got an unexpected keyword argument 'capture_output'
WARNING: '102.pdf' generated an exception: __init__() got an unexpected keyword argument 'capture_output'
...
WARNING: '87.pdf' generated an exception: __init__() got an unexpected keyword argument 'capture_output'
WARNING: '92.pdf' generated an exception: __init__() got an unexpected keyword argument 'capture_output'
WARNING: '96.pdf' generated an exception: __init__() got an unexpected keyword argument 'capture_output'
总共：129页
成功：0页
再次尝试？[Y/n]

**Comment by LML-566** [comment]
高教书院就没有账号那些乱七八糟的东西，但是也会WARNING: '96.pdf' generated an exception: init() got an unexpected keyword argument 'capture_output'导致dec里面啥也没有

**Comment by ScienceZone** [comment]
大佬，还缺啥？我已经将python更新了，还是不行

**Comment by ScienceZone** [comment]
难道是我之前安装的是Win64 OpenSSL v1.1.1d Light的缘故？不能用Light版本？

**Comment by 123-wqy** [comment]
> 大佬，还缺啥？我已经将python更新了，还是不行

你看他报啥错你就装啥...

**Comment by 123-wqy** [comment]
> 高教书院就没有账号那些乱七八糟的东西，但是也会WARNING: '96.pdf' generated an exception: init() got an unexpected keyword argument 'capture_output'导致dec里面啥也没有

就像上面作者说的那样手动解密也不行？

**Comment by LML-566** [comment]
楼上的哥们，不是更新python，而是pip install requests

**Comment by LML-566** [comment]
我试一试手动解密

**Comment by LML-566** [comment]
(python36) E:\Test\kezhiwang\keledge-master>openssl enc -d -aes-128-ecb -K 63742168763555796243614542237a36 -in 1.pdf -out dec.pdf

可以解密，输出了一个dec.pdf可以用PDF软件正常打开

**Comment by ScienceZone** [comment]
已经有了，我是在您的程序文件夹直接右键——在此处打开命令提示符，然后输入指令“main.py -a 【文件名】_authorize.txt”操作的，不知哪里有问题

**Comment by 123-wqy** [comment]
> (python36) E:\Test\kezhiwang\keledge-master>openssl enc -d -aes-128-ecb -K 63742168763555796243614542237a36 -in 1.pdf -out dec.pdf
> 
> 可以解密，输出了一个dec.pdf可以用PDF软件正常打开

那就可能是py的代码哪里出问题了...
问问作者或者重新下载脚本试试

**Comment by ScienceZone** [comment]
你怎么能下载成功的？我安装部署出了问题吗？

**Comment by 123-wqy** [comment]
> 你怎么能下载成功的？我安装部署出了问题吗？

先看看哪里报错嘛...

**Comment by ScienceZone** [comment]
我的是windows 10系统。
命令窗口内容：
E:\Toolbox\应用\下载工具\keledge-master>python main.py -a 【书名】_authorize.txt -t 300
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from inputimeout import inputimeout, TimeoutOccurred
ModuleNotFoundError: No module named 'inputimeout'

**Comment by ScienceZone** [comment]
作者今天将main.py更新了，那倒真有问题了？

**Comment by ygcaicn** [comment]
1. 使用最新代码尝试。
2. 下载依赖的Python包有：requests,inputimeout
```
pip install requests
pip install inputimeout
```

**Comment by ScienceZone** [comment]
安装完inputimeout还有问题！
我是从XX书苑下载的，按照操作，下载时只下载到“authorize.txt”，但是现在给要“passwd”?!怎么回事？
WARNING: [未找到passwd文件，请使用-p指定]
usage: main.py [-h] -a AUTHORIZE_FILE [-p PASSWD_FILE] [-t SLEEP] [--no-guess]

**Comment by 123-wqy** [comment]
pip install inputimeout

> 安装完inputimeout还有问题！
> 我是从XX书苑下载的，按照操作，下载时只下载到“authorize.txt”，但是现在给要“passwd”?!怎么回事？
> WARNING: [未找到passwd文件，请使用-p指定]
> usage: main.py [-h] -a AUTHORIZE_FILE [-p PASSWD_FILE] [-t SLEEP] [--no-guess]

注意一下浏览器在下载文件的时候的提示
“允许下载多个文件”

**Comment by ScienceZone** [comment]
只有一个，我用的360极速

**Comment by ScienceZone** [comment]
问题真是360极速的，换火狐就好了

**Comment by ScienceZone** [comment]
要哭了，还是有问题！！！
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    with open(passwd_file, 'rt') as pwd:
NameError: name 'passwd_file' is not defined

**Comment by Junix-honor** [comment]
Gooreplacer设置完后，打开电子书页面并没有弹出简易教程的窗口，请问要怎么操作？

**Comment by ScienceZone** [comment]
以为成功了，没想到又哭了~
WARNING: '10.pdf' generated an exception: [WinError 183] 当文件已存在时，无法创建该文件。: 'Downloads\\【文档名】_dec'
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    ok = decSplitFiles(enc_dir, dec_dir)
  File "main.py", line 59, in decSplitFiles
    logging.error(ret.stderr.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 10: invalid start byte

**Comment by ScienceZone** [comment]
100多个后遇到问题了
