### ISSUE TITLE
关于下载好enc解密失败得到空dec的问题

### ISSUE THREAD

**Issue by LML-566** [ygcaicn/keledge#3]
问题描述：python程序已经下载好了enc里所有的PDF，但在dec是空的

平台：win10 64位 python36 安装好了Openssl

程序里的异常：WARNING: '98.pdf' generated an exception: __init__() got an unexpected keyword argument 'capture_output'（每一页pdf都出现此错误）

按照作者指引测试测试：(python36) E:\Test\kezhiwang\keledge-master>openssl enc -d -aes-128-ecb -K 63742168763555796243614542237a36 -in 1.pdf -out dec.pdf
对1.pdf测试可以解密，输出了一个dec.pdf可以用PDF软件正常打开

在程序里的进一步测试：
cmd = 'openssl enc -d -aes-128-ecb -K "{}" -in "{}" -out "{}"'.format(p, i, o)
print('p, i, o:', p, i, o)
print('I am here! CMD is OK!')
结果输出：
WARNING: '82.pdf' generated an exception: __init__() got an unexpected keyword argument 'capture_output'
p, i, o: 63742168763555796243614542237a36 E:/Test/kezhiwang/keledge-master/keledge-master\3_enc\96.pdf E:/Test/kezhiwang/keledge-master/keledge-master\3_dec\96.pdf
I am here! CMD is OK!
可以发现路径来说应该是没有问题的
但上面那个WARNING是不是说明没有正常调用CMD，因为单独openssl一个是好的

请问作者该怎么解决？

**Comment by ygcaicn** [comment]
下载最新代码

**Comment by LML-566** [comment]
最新版一样的会报那个警告导致dec里面啥也没有
但我通过一些不可思议的方法运行成了：
它报一个警告：
WARNING: '82.pdf' generated an exception: init() got an unexpected keyword argument 'capture_output'
然后我就找到了：
r = subprocess.run(cmd, capture_output=True)
我就把它改成了r = subprocess.run(cmd)
运行报错
再改回r = subprocess.run(cmd, capture_output=True)
运行成功：
。。。
INFO: file 94.pdf alerady decrypt.
INFO: file 98.pdf alerady decrypt.
INFO: file 99.pdf alerady decrypt.
INFO: file 93.pdf alerady decrypt.
总共：102页
成功：102页

Process finished with exit code 0
dec里面有了正常的pdf
Amazing！

**Comment by LML-566** [comment]
经过两次实验，以上结果非偶然，是都是这样

**Comment by LML-566** [comment]
我仔细看了下程序，
            try:
                ret = future.result()
            except Exception as exc:
                logging.warning('%r generated an exception: %s' % (obj, exc))
从这儿可以看出，作者您是知道会有报错的，但是对于报错的情况您并未做处理，而是任由他输出错误信息。请问这具体是什么问题呢？
不知道我上面的测试是否有利于作者您修改。
错误来源应该就是这句：r = subprocess.run(cmd, capture_output=True)
是否传入的capture_output这个参数不正确？
但是疑问就是我删去capture_output=True就会报错，再次添加上却没有了之前的 init() got an unexpected keyword argument 'capture_output'，而是正常运行。
这中间按理来说第一次和第三次程序是一模一样的，但第一次有错误，第三次没错误，那第二次报错后是产生了什么文件之类的，让第三次不报错？

作者你自己在运行过程中第一次运行r = subprocess.run(cmd, capture_output=True)是否有错？

**Comment by LML-566** [comment]
请问作者是在什么平台上测试的，会不会因为平台的差异导致的此错误？

**Comment by LML-566** [comment]
已解决！
探索成功：
确实是那句r = subprocess.run(cmd, capture_output=True)有问题
第三次运行没问题又说明它没问题
我在：https://www.cnblogs.com/lijinlei521/p/10873601.html
发现capture_output =true 相当于stdout=PIPE and stderr=PIPE
于是修改如下：
r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
运行：
INFO: page 91.pdf decrypt ok. 
INFO: page 92.pdf decrypt ok. 
INFO: page 96.pdf decrypt ok. 
INFO: page 94.pdf decrypt ok. 
INFO: page 95.pdf decrypt ok. 
INFO: page 93.pdf decrypt ok. 
INFO: page 97.pdf decrypt ok.

就不会出现之前的
WARNING: '82.pdf' generated an exception: init() got an unexpected keyword argument 'capture_output'

到此解决，多谢作者之前的耐心解惑。
