### ISSUE TITLE
关于程序的一些疑问

### ISSUE THREAD

**Issue by LML-566** [ygcaicn/keledge#4]
h = '''
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Sec-Fetch-Dest: document
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
Referer: https://www.keledge.com
Accept-Encoding: gzip, deflate, br
Accept-Language: en,zh-CN;q=0.9,zh;q=0.8,pt;q=0.7

'''

headers = dict([i.split(': ', 1) for i in h.split('\n') if i != ''])
headers = {}

为什么headers = {}？

**Comment by ygcaicn** [comment]
屏蔽了上面的headers，用requests默认的即可

**Comment by LML-566** [comment]
也就是不用headers
r = requests.get(url)的意思喽
