### ISSUE TITLE
脚本疑问

### ISSUE THREAD

**Issue by Junix-honor** [ygcaicn/keledge#6]
Gooreplacer设置完后，打开电子书页面并没有显示简易教程的窗口，请问要怎么操作？

**Comment by ygcaicn** [comment]
F12查看有无报错，尝试ui_init()手动触发

**Comment by 858043016** [comment]
我也是没有建议教程的窗口，
console里面有两个黄色告警：
‘’‘
DevTools failed to parse SourceMap: https://cdn.keledge.com/files/js/hls.j.map
pdfReader?url=https%3A%2F%2Fgateway.keledge.com%2Ftransfer%2Faqr%2Fauthorize&contentexternalid=P00001-01-978-7-121-28422-9-Pdf&id=62678&organizationExternalId=&objectType=104&process=&tocValue=:1 A cookie associated with a cross-site resource at http://baidu.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
pdfReader?url=https%3A%2F%2Fgateway.keledge.com%2Ftransfer%2Faqr%2Fauthorize&contentexternalid=P00001-01-978-7-121-28422-9-Pdf&id=62678&organizationExternalId=&objectType=104&process=&tocValue=:1 A cookie associated with a cross-site resource at http://hm.baidu.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
DevTools failed to parse SourceMap: https://cdn.keledge.com/files/js/hls.js.map
’‘’
ui_init()不知道怎么使用，是在console输入吗，提示未定义

**Comment by ygcaicn** [comment]
哪个平台？

**Comment by 858043016** [comment]
chrome win10




------------------&nbsp;Original&nbsp;------------------

**Comment by 123-wqy** [comment]
如果是可知平台，试试修改Source为https://cdn.keledge.com/web/static/js/3.878b418d7f1298f150e8.\S+.js

**Comment by Junix-honor** [comment]
> 如果是可知平台，试试修改Source为[https://cdn.keledge.com/web/static/js/3.878b418d7f1298f150e8.\S+.js](https://cdn.keledge.com/web/static/js/3.878b418d7f1298f150e8.%5CS+.js)

改了之后电子书页面打不开了

**Comment by 123-wqy** [comment]
emmm...
加载网页的时候看F12的“网络”里面有没有对js的307重定向，能不能看到nice2.js的加载

**Comment by Junix-honor** [comment]
> “网络”里面没有对js的307重定

Failed to load resource: net::ERR_INVALID_URL
DevTools failed to parse SourceMap: https://cdn.keledge.com/files/js/hls.js.map

**Comment by 858043016** [comment]
> 如果是可知平台，试试修改Source为[https://cdn.keledge.com/web/static/js/3.878b418d7f1298f150e8.\S+.js](https://cdn.keledge.com/web/static/js/3.878b418d7f1298f150e8.%5CS+.js)
我修改之后可以打开电子书
