### ISSUE TITLE
高教的应该更新了

### ISSUE THREAD

**Issue by 858043016** [ygcaicn/keledge#8]
我改成 https://ebook.hep.com.cn/ebooks/read/static/js/0.5704ef752a837ce4f7cf.\S+.js
还是不对

**Comment by 123-wqy** [comment]
https://ebook.hep.com.cn/ebooks/read/static/js/3.f91035baf333fda1fee9.\S+.js

**Comment by 123-wqy** [comment]
话说今天keledge平台貌似有问题啊...

**Comment by ygcaicn** [comment]
keledge已出应对措施，某些情况会向https://gateway.keledge.com/transfer/risk/check Post信息，存在风险会暂时性封号，表现为所有数据都无法加载，包括首页。目前了解到按F12会触发上报，大家慎重操作。

![image](https://user-images.githubusercontent.com/17684070/77080759-a78b7680-6a34-11ea-89a1-88233b385c00.png)

目前修改Source地址仍能使用。

为了大家更长久的使用，暂时不再更新。
